from __future__ import annotations

from app.venues.models import (
    VenueAuthStyle,
    VenueCapabilities,
    VenueDefinition,
    VenueExecutionStyle,
    VenueId,
    VenueType,
)

VENUE_REGISTRY: tuple[VenueDefinition, ...] = (
    VenueDefinition(
        venue_id=VenueId.BINANCE,
        display_name="Binance",
        venue_type=VenueType.CEX,
        market_adapter_module="app.exchanges.binance.BinanceClient",
        execution_adapter_module="app.execution_adapters.paper.PaperExecutionAdapter",
        execution_style=VenueExecutionStyle.PAPER_ONLY,
        auth_style=VenueAuthStyle.API_KEY_SECRET,
        capabilities=VenueCapabilities(
            supports_snapshots=True,
            supports_place_order=False,
            supports_cancel_order=False,
            supports_order_status=False,
            supports_positions=False,
            supports_balances=False,
            paper_supported=True,
            live_supported_now=False,
            supports_rest_trading_api=True,
            supports_private_websocket_trading=True,
            supports_signed_actions=False,
            supports_sdk_recommended=False,
            execution_interface_notes="Classic signed private REST endpoints plus user-data websocket stream for state updates.",
        ),
        notes="Market data adapter is active. Execution is still paper-only here despite Binance private trading APIs being available upstream.",
    ),
    VenueDefinition(
        venue_id=VenueId.OKX,
        display_name="OKX",
        venue_type=VenueType.CEX,
        market_adapter_module="app.exchanges.okx.OkxClient",
        execution_adapter_module="app.execution_adapters.paper.PaperExecutionAdapter",
        execution_style=VenueExecutionStyle.PAPER_ONLY,
        auth_style=VenueAuthStyle.API_KEY_SECRET,
        capabilities=VenueCapabilities(
            supports_snapshots=True,
            supports_place_order=False,
            supports_cancel_order=False,
            supports_order_status=False,
            supports_positions=False,
            supports_balances=False,
            paper_supported=True,
            live_supported_now=False,
            supports_rest_trading_api=True,
            supports_private_websocket_trading=True,
            supports_signed_actions=False,
            supports_sdk_recommended=False,
            execution_interface_notes="Classic authenticated REST + private websocket model with exchange-managed API key/secret/passphrase.",
        ),
        notes="Market data adapter is active. Execution is still paper-only here despite OKX private trading APIs being available upstream.",
    ),
    VenueDefinition(
        venue_id=VenueId.HYPERLIQUID,
        display_name="Hyperliquid",
        venue_type=VenueType.DEX,
        market_adapter_module="app.exchanges.hyperliquid.HyperliquidClient",
        execution_adapter_module="app.execution_adapters.paper.PaperExecutionAdapter",
        execution_style=VenueExecutionStyle.PAPER_ONLY,
        auth_style=VenueAuthStyle.WALLET_SIGNATURE,
        capabilities=VenueCapabilities(
            supports_snapshots=True,
            supports_place_order=False,
            supports_cancel_order=False,
            supports_order_status=False,
            supports_positions=False,
            supports_balances=False,
            paper_supported=True,
            live_supported_now=False,
            supports_rest_trading_api=False,
            supports_private_websocket_trading=False,
            supports_signed_actions=True,
            supports_sdk_recommended=True,
            execution_interface_notes="Signed action payloads sent to the exchange endpoint and account state queried via info endpoint.",
        ),
        notes="Market data adapter is active. Execution is still paper-only; Hyperliquid live integration requires wallet/action signing flows.",
    ),
    VenueDefinition(
        venue_id=VenueId.LIGHTER,
        display_name="Lighter",
        venue_type=VenueType.DEX,
        market_adapter_module="app.exchanges.lighter.LighterClient",
        execution_adapter_module="app.execution_adapters.paper.PaperExecutionAdapter",
        execution_style=VenueExecutionStyle.PAPER_ONLY,
        auth_style=VenueAuthStyle.WALLET_SIGNATURE,
        capabilities=VenueCapabilities(
            supports_snapshots=True,
            supports_place_order=False,
            supports_cancel_order=False,
            supports_order_status=False,
            supports_positions=False,
            supports_balances=False,
            paper_supported=True,
            live_supported_now=False,
            supports_rest_trading_api=True,
            supports_private_websocket_trading=True,
            supports_signed_actions=True,
            supports_sdk_recommended=True,
            execution_interface_notes="Transaction-like flow using API-key auth tokens and signed payloads; SDK manages nonce/signature details.",
        ),
        notes="Market data adapter is active. Execution is still paper-only; Lighter live integration depends on API-key signing and transaction semantics.",
    ),
)


def list_venue_definitions() -> list[VenueDefinition]:
    return [item.model_copy(deep=True) for item in VENUE_REGISTRY]
