EXPECTED_FUNDING_PERIOD_HOURS = {
    "binance": 8,
    "okx": 8,
    "hyperliquid": 8,
    "lighter": 4,
}

SNAPSHOT_STALE_WARNING_MS = 120_000
SNAPSHOT_STALE_BLOCK_MS = 300_000

FUNDING_WINDOW_TOLERANCE_HOURS = 0.5

MARK_INDEX_BASIS_WARNING = 0.05
MARK_INDEX_BASIS_SUSPICIOUS = 0.15

LAST_MARK_BASIS_WARNING = 0.05
LAST_MARK_BASIS_SUSPICIOUS = 0.15

CROSS_EXCHANGE_PRICE_WARNING = 0.01
CROSS_EXCHANGE_PRICE_SUSPICIOUS = 0.03
CROSS_EXCHANGE_PRICE_BLOCK = 0.05
